// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Enriches lead data using an LLM to extract insights and identify key contacts, leveraging third-party tool connectors like Clearbit and Hunter.io.
 *
 * - enrichLeadDataWithLLM - A function that handles the lead enrichment process.
 * - EnrichLeadDataWithLLMInput - The input type for the enrichLeadDataWithLLM function.
 * - EnrichLeadDataWithLLMOutput - The return type for the enrichLeadDataWithLLM function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EnrichLeadDataWithLLMInputSchema = z.object({
  leadName: z.string().describe('The name of the lead (company or person).'),
  leadDescription: z.string().describe('A detailed description of the lead.'),
  existingData: z.record(z.any()).optional().describe('Existing lead data to be enriched.'),
});
export type EnrichLeadDataWithLLMInput = z.infer<typeof EnrichLeadDataWithLLMInputSchema>;

const EnrichLeadDataWithLLMOutputSchema = z.object({
  enrichedData: z.record(z.any()).describe('The enriched lead data.'),
  keyContacts: z.array(z.string()).describe('A list of key contacts identified for the lead.'),
  summary: z.string().describe('A summary of the lead and its potential value.'),
});
export type EnrichLeadDataWithLLMOutput = z.infer<typeof EnrichLeadDataWithLLMOutputSchema>;

export async function enrichLeadDataWithLLM(input: EnrichLeadDataWithLLMInput): Promise<EnrichLeadDataWithLLMOutput> {
  return enrichLeadDataWithLLMFlow(input);
}

const prompt = ai.definePrompt({
  name: 'enrichLeadDataWithLLMPrompt',
  input: {schema: EnrichLeadDataWithLLMInputSchema},
  output: {schema: EnrichLeadDataWithLLMOutputSchema},
  prompt: `You are an AI-powered lead enrichment service. Your goal is to enrich lead data and extract key insights.

  Existing Data: {{existingData}}

  Lead Name: {{leadName}}
  Lead Description: {{leadDescription}}

  Instructions:
  1.  Analyze the lead description and name to identify key information such as industry, company size, and potential needs.
  2.  Use external tools and connectors like Clearbit and Hunter.io (if available - assume they are and the results will be automatically merged) to gather additional information about the lead.
  3.  Identify key contacts within the lead (if applicable), focusing on decision-makers and influencers.
  4.  Generate a summary of the lead, highlighting its potential value and key insights.
  5.  Return the enriched data, key contacts, and summary in the specified JSON format.

  Output format: JSON
  {
    "enrichedData": {},
    "keyContacts": [],
    "summary": ""
  }`,
});

const enrichLeadDataWithLLMFlow = ai.defineFlow(
  {
    name: 'enrichLeadDataWithLLMFlow',
    inputSchema: EnrichLeadDataWithLLMInputSchema,
    outputSchema: EnrichLeadDataWithLLMOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
